'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Business_Units_Plants
    Public Property Id As Integer
    Public Property Description As String
    Public Property BusinessUnit As Integer
    Public Property PlantCode As String
    Public Property Country As String
    Public Property Identifier As String
    Public Property ShiftDurationHrs As Nullable(Of Integer)

    Public Overridable Property Business_Units As Business_Units
    Public Overridable Property Financial_Periods As ICollection(Of Financial_Periods) = New HashSet(Of Financial_Periods)
    Public Overridable Property Plants_Locations As ICollection(Of Plants_Locations) = New HashSet(Of Plants_Locations)
    Public Overridable Property Plants_Shifts As ICollection(Of Plants_Shifts) = New HashSet(Of Plants_Shifts)
    Public Overridable Property ShiftForemansReports As ICollection(Of ShiftForemansReport) = New HashSet(Of ShiftForemansReport)
    Public Overridable Property Stocks As ICollection(Of Stock) = New HashSet(Of Stock)

End Class
