'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Device
    Public Property Id As Integer
    Public Property Description As String
    Public Property IP As String
    Public Property Type As String
    Public Property Status As String
    Public Property MAC As String
    Public Property SwitchPort As Nullable(Of Integer)
    Public Property Switch As String
    Public Property SerialNumber As String
    Public Property HardwareVersion As String
    Public Property SoftwareVersion As String
    Public Property StorageInformation As String
    Public Property NetworkInformation As String
    Public Property LocalWebServerUrlPORT As String
    Public Property RequiresUpdate As Nullable(Of Boolean)
    Public Property LastCheckin As Nullable(Of Date)
    Public Property LastReportedStatus As String
    Public Property NetworkConfigIP As String
    Public Property NetworkConfigSubnet As String
    Public Property NetworkConfigGateway As String
    Public Property NetworkConfigDNS As String
    Public Property LockedOut As Nullable(Of Boolean)
    Public Property LockedOutBy As String
    Public Property LockedOutOn As Nullable(Of Date)
    Public Property SecurityKey As String
    Public Property CurrentOperatorId As String
    Public Property RequiresSupport As Nullable(Of Boolean)
    Public Property Waypoint As Nullable(Of Integer)

    Public Overridable Property Waypoint1 As Waypoint

End Class
