'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Handling_Units
    Public Property Id As Integer
    Public Property SSCC As String
    Public Property Product As Nullable(Of Integer)
    Public Property Created As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property Status As String
    Public Property NumberBank As Nullable(Of Integer)
    Public Property Device As String
    Public Property Batch As Nullable(Of Integer)
    Public Property ScannedCode As String
    Public Property Horse As String
    Public Property Trailer As String
    Public Property Berth As String
    Public Property Description As String

    Public Overridable Property Handling_Units_Movements As ICollection(Of Handling_Units_Movements) = New HashSet(Of Handling_Units_Movements)
    Public Overridable Property Production_Batches As Production_Batches
    Public Overridable Property Product1 As Product
    Public Overridable Property Waypoints_NumberBanks As Waypoints_NumberBanks

End Class
