'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Handling_Units_Movements
    Public Property Id As Integer
    Public Property Handling_UnitId As Nullable(Of Integer)
    Public Property Device As String
    Public Property Created As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property Type As String
    Public Property Status As String
    Public Property Horse As String
    Public Property Trailer As String
    Public Property Berth As String
    Public Property Source As String
    Public Property Destination As String
    Public Property Waypoint As String

    Public Overridable Property Handling_Units As Handling_Units

End Class
