'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Loadslip
    Public Property Id As Integer
    Public Property LoadReference As String
    Public Property Driver As String
    Public Property Horse As String
    Public Property Trailer As String
    Public Property Trailer2 As String
    Public Property Created As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property Notes As String
    Public Property PlantId As Nullable(Of Integer)
    Public Property FromLocation As String
    Public Property ToLocation As String
    Public Property IsFullLoad As Nullable(Of Boolean)
    Public Property IsSharedLoad As Nullable(Of Boolean)
    Public Property Status As String
    Public Property Transporter As String
    Public Property LoadedBy As String
    Public Property Loaded As Nullable(Of Date)
    Public Property Type As String
    Public Property Device As String
    Public Property Waypoint As String

    Public Overridable Property Loadslips_Details As ICollection(Of Loadslips_Details) = New HashSet(Of Loadslips_Details)

End Class
