'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Log
    Public Property Id As Integer
    Public Property Description As String
    Public Property RelatedRecord As String
    Public Property RecordType As String
    Public Property [Event] As String
    Public Property AlertLevel As String
    Public Property EventRaised As Nullable(Of Date)

End Class
