'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Production_Batches
    Public Property Id As Integer
    Public Property Description As String
    Public Property Type As String
    Public Property Status As String
    Public Property Shift As Nullable(Of Integer)
    Public Property BatchDate As Nullable(Of Date)
    Public Property BatchCreated As Nullable(Of Date)
    Public Property BatchEnded As Nullable(Of Date)
    Public Property Plant As String

    Public Overridable Property Handling_Units As ICollection(Of Handling_Units) = New HashSet(Of Handling_Units)
    Public Overridable Property Plants_Shifts As Plants_Shifts
    Public Overridable Property QC_Scales_Readings As ICollection(Of QC_Scales_Readings) = New HashSet(Of QC_Scales_Readings)
    Public Overridable Property ShiftForemansReports As ICollection(Of ShiftForemansReport) = New HashSet(Of ShiftForemansReport)

End Class
