'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Product
    Public Property Id As Integer
    Public Property Description As String
    Public Property PLU As Nullable(Of Integer)
    Public Property Type As String
    Public Property Packaging As String
    Public Property ConsumerUnits As Nullable(Of Integer)
    Public Property SalesUnits As Nullable(Of Integer)
    Public Property TargetWeight As Nullable(Of Decimal)
    Public Property UOM As String
    Public Property TareWeight As String
    Public Property ConsumerBarcode As String
    Public Property SalesUnitBarcode As String
    Public Property Commodity As String
    Public Property ProducedBy As String
    Public Property Status As String
    Public Property HUTargetWeight As Nullable(Of Decimal)
    Public Property ExpiryDays As Nullable(Of Integer)
    Public Property Labels As Nullable(Of Integer)
    Public Property QCSampleSize As Nullable(Of Integer)

    Public Overridable Property Handling_Units As ICollection(Of Handling_Units) = New HashSet(Of Handling_Units)
    Public Overridable Property QC_Scales_Readings As ICollection(Of QC_Scales_Readings) = New HashSet(Of QC_Scales_Readings)

End Class
