'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QC_Scales_Readings
    Public Property Id As Integer
    Public Property ReadingDate As Date
    Public Property Product As Integer
    Public Property [Operator] As Nullable(Of Integer)
    Public Property S1 As Nullable(Of Decimal)
    Public Property S2 As Nullable(Of Decimal)
    Public Property S3 As Nullable(Of Decimal)
    Public Property S4 As Nullable(Of Decimal)
    Public Property Median As Nullable(Of Decimal)
    Public Property Tare As Nullable(Of Decimal)
    Public Property Result As String
    Public Property Status As String
    Public Property Result_Action As String
    Public Property Target As Nullable(Of Decimal)
    Public Property Batch As Nullable(Of Integer)
    Public Property QC_Station As Nullable(Of Integer)
    Public Property UOM As String
    Public Property QC_Scale As Nullable(Of Integer)

    Public Overridable Property Production_Batches As Production_Batches
    Public Overridable Property Product1 As Product
    Public Overridable Property QC_Scales As QC_Scales
    Public Overridable Property QC_Scales_Stations As QC_Scales_Stations

End Class
