'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QC_Scales
    Public Property Id As Integer
    Public Property Description As String
    Public Property Make As String
    Public Property Model As String
    Public Property LoadCapacity As Nullable(Of Decimal)
    Public Property UOM As String
    Public Property Device As Nullable(Of Integer)
    Public Property SoftwareVersion As String
    Public Property BoardVersion As String
    Public Property SerialNumber As String

    Public Overridable Property QC_Scales_Readings As ICollection(Of QC_Scales_Readings) = New HashSet(Of QC_Scales_Readings)
    Public Overridable Property QC_Scales_Stations As ICollection(Of QC_Scales_Stations) = New HashSet(Of QC_Scales_Stations)

End Class
