'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class QC_Scales_Stations
    Public Property Id As Integer
    Public Property Description As String
    Public Property Location As Nullable(Of Integer)
    Public Property Functions As String
    Public Property QC_Scale As Nullable(Of Integer)

    Public Overridable Property Plants_Locations As Plants_Locations
    Public Overridable Property QC_Scales As QC_Scales
    Public Overridable Property QC_Scales_Readings As ICollection(Of QC_Scales_Readings) = New HashSet(Of QC_Scales_Readings)

End Class
