'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class zzSAPIntegrationTSHEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=zzSAPIntegrationTSHEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property SAPInvoices() As DbSet(Of SAPInvoice)
    Public Overridable Property SAPMtlDocs() As DbSet(Of SAPMtlDoc)
    Public Overridable Property SAPTransactions() As DbSet(Of SAPTransaction)
    Public Overridable Property WBCompletedWeighings() As DbSet(Of WBCompletedWeighing)
    Public Overridable Property WBEvents() As DbSet(Of WBEvent)
    Public Overridable Property WBTransactions() As DbSet(Of WBTransaction)
    Public Overridable Property zTraceIn_MB51Data() As DbSet(Of zTraceIn_MB51Data)
    Public Overridable Property zTraceIn_SAPConfirmations() As DbSet(Of zTraceIn_SAPConfirmations)
    Public Overridable Property zTraceIn_SAPDeliveryHdrs() As DbSet(Of zTraceIn_SAPDeliveryHdrs)
    Public Overridable Property zTraceIn_SAPDeliveryLines() As DbSet(Of zTraceIn_SAPDeliveryLines)
    Public Overridable Property zTraceIn_SAPMaterials() As DbSet(Of zTraceIn_SAPMaterials)
    Public Overridable Property zTraceOut_DeliveryHdr() As DbSet(Of zTraceOut_DeliveryHdr)
    Public Overridable Property zTraceOut_DeliveryLines() As DbSet(Of zTraceOut_DeliveryLines)
    Public Overridable Property zTraceOut_SSCCMovements() As DbSet(Of zTraceOut_SSCCMovements)
    Public Overridable Property zTraceOut_SSCCUnit() As DbSet(Of zTraceOut_SSCCUnit)
    Public Overridable Property zTraceOut_Waypoints() As DbSet(Of zTraceOut_Waypoints)

End Class
