'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAPInvoice
    Public Property AutoKey As Integer
    Public Property SourceSystem As String
    Public Property SrcMessageID As String
    Public Property SrcMessageTime As Nullable(Of Date)
    Public Property SrcInvoiceNo As String
    Public Property SrcDocStatus As String
    Public Property SrcRefDocNr As String
    Public Property Src_InvoicedWtKg As Nullable(Of Decimal)
    Public Property SrcDoc_PostingDate As Nullable(Of Date)
    Public Property SrcDoc_PostingTime As Nullable(Of System.TimeSpan)
    Public Property SrcDoc_ChangeUser As String
    Public Property Src_IntegrationTime As Nullable(Of Date)
    Public Property Src_IntegrationUser As String

End Class
