'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAPMtlDoc
    Public Property AutoKey As Integer
    Public Property WBID As String
    Public Property TranType As String
    Public Property SourceSystem As String
    Public Property SrcMtlDocNum As String
    Public Property SrcMtlDocYear As String
    Public Property SrcMtlDocType As String
    Public Property SrcMtlDocLine As String
    Public Property SrcMessageID As String
    Public Property SrcMessageTime As Nullable(Of Date)
    Public Property SrcMessageActive As String
    Public Property SrcDocStatus As String
    Public Property Src_MtlDcDate As Nullable(Of Date)
    Public Property Src_PostingDate As Nullable(Of Date)
    Public Property Src_MovementType As String
    Public Property Src_DeliveryNoteNo As String
    Public Property Src_HeaderText As String
    Public Property Src_BillOfLading As String
    Public Property Src_PONumber As String
    Public Property Src_MATNR As String
    Public Property Src_GRQty As Nullable(Of Decimal)
    Public Property Src_GRUOM As String
    Public Property Src_GRUser As String
    Public Property Src_GRDate As Nullable(Of Date)
    Public Property Src_GRTime As Nullable(Of System.TimeSpan)
    Public Property Src_IntegrationTime As Nullable(Of Date)
    Public Property Src_IntegrationUser As String
    Public Property WWMessageStatus As String
    Public Property WWProcessedtime As Nullable(Of Date)

End Class
