'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SAPTransaction
    Public Property AutoKey As Integer
    Public Property SourceSystem As String
    Public Property SrcMessageID As String
    Public Property SrcMessageTime As Nullable(Of Date)
    Public Property SrcDocStatus As String
    Public Property Src_ExpectedWtKg As Nullable(Of Decimal)
    Public Property SrcRefDocNr As String
    Public Property SrcDoc_KUNAG As String
    Public Property SrcDoc_KUNNR As String
    Public Property SrcDoc_ChangeTime As Nullable(Of Date)
    Public Property SrcDoc_ChangeUser As String
    Public Property Src_IntegrationTime As Nullable(Of Date)
    Public Property Src_IntegrationUser As String
    Public Property SrcDoc_KUNAG_NAME As String
    Public Property SrcDoc_KUNNR_NAME As String
    Public Property SrcDoc_VBELN_VA As String
    Public Property SrcDoc_BSTNK As String

End Class
