'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ShiftForemansReport
    Public Property Id As Integer
    Public Property Description As String
    Public Property Type As String
    Public Property Created As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property ShiftId As Nullable(Of Integer)
    Public Property PlantId As Nullable(Of Integer)
    Public Property BatchId As Nullable(Of Integer)

    Public Overridable Property Business_Units_Plants As Business_Units_Plants
    Public Overridable Property Plants_Shifts As Plants_Shifts
    Public Overridable Property Production_Batches As Production_Batches

End Class
