'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Software_Development
    Public Property Id As Integer
    Public Property Description As String
    Public Property Created As Date
    Public Property LongDescription As String
    Public Property Status As String
    Public Property Type As String
    Public Property PlannedDate As Date
    Public Property StartDate As Nullable(Of Date)
    Public Property EndDate As Nullable(Of Date)
    Public Property DueDate As Nullable(Of Date)
    Public Property Priority As String
    Public Property PlannedHours As Nullable(Of Integer)
    Public Property ActualHours As Nullable(Of Integer)
    Public Property Tested As Nullable(Of Date)
    Public Property PO As Nullable(Of Integer)
    Public Property QuoteNumber As String
    Public Property InvoiceNumber As String
    Public Property Paid As Nullable(Of Date)
    Public Property Completed As Nullable(Of Date)

End Class
