'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Software_Packages
    Public Property Id As Integer
    Public Property Description As String
    Public Property Type As String
    Public Property Status As String
    Public Property Version As String
    Public Property ReleaseDate As Nullable(Of Date)
    Public Property ExpiryDate As Nullable(Of Date)
    Public Property PackageLocation As String
    Public Property PackageExecuteScriptLocation As String

End Class
