'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Software_Settings
    Public Property Id As String
    Public Property SettingName As String
    Public Property SettingValue As String
    Public Property SettingGroup As String
    Public Property SettingSubGroup As String

End Class
