'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Stock_Movements
    Public Property Id As Integer
    Public Property StockId As Integer
    Public Property CreatedBy As String
    Public Property Created As Nullable(Of Date)
    Public Property MovedFrom As String
    Public Property MovedTo As String
    Public Property BatchId As Nullable(Of Integer)
    Public Property ShiftId As Nullable(Of Integer)
    Public Property PlantId As Nullable(Of Integer)
    Public Property BusinessId As Nullable(Of Integer)
    Public Property StockAffected As Nullable(Of Integer)
    Public Property Status As String

    Public Overridable Property Stock As Stock

End Class
