'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Waypoint
    Public Property Id As Integer
    Public Property Description As String
    Public Property Type As String
    Public Property Status As String
    Public Property UOM As String
    Public Property LoadCapcity As String
    Public Property HasPrinter As Nullable(Of Boolean)
    Public Property HasScanner As Nullable(Of Boolean)
    Public Property Location As Nullable(Of Integer)

    Public Overridable Property Devices As ICollection(Of Device) = New HashSet(Of Device)
    Public Overridable Property Plants_Locations As Plants_Locations
    Public Overridable Property Waypoints_Configurations As ICollection(Of Waypoints_Configurations) = New HashSet(Of Waypoints_Configurations)
    Public Overridable Property Waypoints_NumberBanks As ICollection(Of Waypoints_NumberBanks) = New HashSet(Of Waypoints_NumberBanks)

End Class
