'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Waypoints_NumberBanks
    Public Property Id As Integer
    Public Property Prefix As String
    Public Property Bank As String
    Public Property Root As String
    Public Property FirstNumber As Nullable(Of Integer)
    Public Property LastNumber As Nullable(Of Integer)
    Public Property LastIssued As String
    Public Property Created As Nullable(Of Date)
    Public Property Reserved As Nullable(Of Date)
    Public Property Released As Nullable(Of Date)
    Public Property Depleted As Nullable(Of Date)
    Public Property Waypoint As Nullable(Of Integer)
    Public Property Device As String
    Public Property Status As String

    Public Overridable Property Handling_Units As ICollection(Of Handling_Units) = New HashSet(Of Handling_Units)
    Public Overridable Property Waypoint1 As Waypoint

End Class
