'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WBCompletedWeighing
    Public Property AutoKey As Integer
    Public Property WBID As String
    Public Property TranType As String
    Public Property SrcDocNum As String
    Public Property SrcDocType As String
    Public Property SourceSystem As String
    Public Property WWMessageID As String
    Public Property WWMessageTime As Nullable(Of Date)
    Public Property WW_Direction As String
    Public Property WW_ActualWtKg As Nullable(Of Decimal)
    Public Property WW_ActualDate As Nullable(Of Date)
    Public Property WW_ActualReg As String
    Public Property WW_ActualDriver As String
    Public Property WW_ActualDeviationUnder As Nullable(Of Decimal)
    Public Property WW_ActualDeviationOver As Nullable(Of Decimal)
    Public Property WW_PO_CumulativeDlvy As Nullable(Of Decimal)
    Public Property WW_W1_D As Nullable(Of Date)
    Public Property WW_W1_T As Nullable(Of System.TimeSpan)
    Public Property WW_W1_MASS As Nullable(Of Decimal)
    Public Property WW_W2_D As Nullable(Of Date)
    Public Property WW_W2_T As Nullable(Of System.TimeSpan)
    Public Property WW_W2_MASS As Nullable(Of Decimal)
    Public Property VendorDeliveryRef As String
    Public Property SrcMessageStatus As String
    Public Property SrcProcessedtime As Nullable(Of Date)
    Public Property WW_TicketNo As String
    Public Property TotalPalletCount As Nullable(Of Integer)
    Public Property TotalPalletWeight As Nullable(Of Decimal)
    Public Property TotalPalletWeightKgs As Nullable(Of Decimal)

End Class
