'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WBTransaction
    Public Property AutoKey As Integer
    Public Property WBID As String
    Public Property TranType As String
    Public Property SrcDocNum As String
    Public Property SrcDocType As String
    Public Property SourceSystem As String
    Public Property SrcMessageID As String
    Public Property SrcMessageTime As Nullable(Of Date)
    Public Property SrcDocStatus As String
    Public Property Src_ExpectedWtKg As Nullable(Of Decimal)
    Public Property Src_ExpectedDate As Nullable(Of Date)
    Public Property Src_ExpectedReg As String
    Public Property Src_ExpectedDriver As String
    Public Property Src_AllowedTolUnder As Nullable(Of Decimal)
    Public Property Src_AllowedTolOver As Nullable(Of Decimal)
    Public Property Src_PO_CumulativeDlvy As Nullable(Of Decimal)
    Public Property SrcDoc_ChangeTime As Nullable(Of Date)
    Public Property SrcDoc_ChangeUser As String
    Public Property Src_IntegrationTime As Nullable(Of Date)
    Public Property Src_IntegrationUser As String
    Public Property SrcDoc_PartnerNumber As String
    Public Property SrcDoc_PartnerType As String
    Public Property Src_RefDocCount As Nullable(Of Short)
    Public Property Src_ExpiryDays As Nullable(Of Short)
    Public Property WWMessageStatus As String
    Public Property WWProcessedtime As Nullable(Of Date)
    Public Property SrcDoc_PartnerName As String
    Public Property BulkFlag As String
    Public Property VendorName As String

End Class
