'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceOut_SSCCUnit
    Public Property Id As Integer
    Public Property WERKS As String
    Public Property MATNR As String
    Public Property SSCC As String
    Public Property WaypointId As Nullable(Of Integer)
    Public Property Waypoint As String
    Public Property Created As Nullable(Of Date)
    Public Property CreatedTime As Nullable(Of System.TimeSpan)
    Public Property CreatedDate As Nullable(Of Date)
    Public Property CreatedBy As String
    Public Property ActualWeight As Nullable(Of Double)
    Public Property ScannedGTIN As String
    Public Property Label_GTIN As String
    Public Property Label_Description As String
    Public Property Label_Country As String
    Public Property PData_DateCode As String
    Public Property PData_DateTime As String
    Public Property PData_BatchCode As String
    Public Property PData_BestBefore As String
    Public Property PDet_PCode As String
    Public Property PDet_OrdUnits As Nullable(Of Integer)
    Public Property PDet_ConsUnits As Nullable(Of Integer)
    Public Property PDet_NetWt As Nullable(Of Double)

End Class
