'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceIn_SAPMaterials
    Public Property SYSID As String
    Public Property MANDT As String
    Public Property WERKS As String
    Public Property MATNR As String
    Public Property MAKTX As String
    Public Property GTIN_CON As String
    Public Property GTIN_HU As String
    Public Property GTIN_Level1 As String
    Public Property GTIN_Level2 As String
    Public Property NetWt_CON As Decimal
    Public Property NetWt_HU As Decimal
    Public Property NetWt_Level1 As Nullable(Of Decimal)
    Public Property NetWt_Level2 As Nullable(Of Decimal)
    Public Property TareWt_CON As Nullable(Of Decimal)
    Public Property TareWt_HU As Nullable(Of Decimal)
    Public Property TareWt_Level1 As Nullable(Of Decimal)
    Public Property TareWt_Level2 As Nullable(Of Decimal)
    Public Property HUQty_CON As Decimal
    Public Property HUQty_Level1 As Decimal
    Public Property HUQty_Level2 As Decimal
    Public Property SAPUOM_CON As String
    Public Property SAPUOM_HU As String
    Public Property SAPUOM_Level1 As String
    Public Property SAPUOM_Level2 As String
    Public Property SAPUOM_Base As String
    Public Property SAPUOM_Sales As String
    Public Property QCUOM As String
    Public Property WtCatUOM As String
    Public Property ProductType As String
    Public Property ProductWtCat As Decimal
    Public Property BulkFlag As String
    Public Property DateFirstAdded As Nullable(Of Date)
    Public Property DateLastUpdated As Nullable(Of Date)
    Public Property ReadStatus As Nullable(Of Decimal)
    Public Property Retired As String
    Public Property RetirementDate As Nullable(Of Date)

End Class
