'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceIn_SAPDeliveryHdrs
    Public Property AutoKey As Nullable(Of Integer)
    Public Property SourceSystem As String
    Public Property SrcRefDocNr As String
    Public Property ExportDate As Date
    Public Property ExportTime As System.TimeSpan
    Public Property VSTEL As String
    Public Property VKORG As String
    Public Property LFART As String
    Public Property KFGRP As String
    Public Property TCODE As String
    Public Property INCO2 As String
    Public Property VBTYP As String
    Public Property BRGEW As Nullable(Of Decimal)
    Public Property NTGEW As Nullable(Of Decimal)
    Public Property GEWEI As String

End Class
