'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceOut_SSCCMovements
    Public Property Id As Integer
    Public Property SSCC As String
    Public Property WaypointID As Integer
    Public Property WaypointTime As Byte()
    Public Property MovementDirection As String
    Public Property MovementDesc As String
    Public Property OperatorID As String
    Public Property NewStatus As String
    Public Property MovementTime As Nullable(Of Date)

End Class
