'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceIn_SAPDeliveryLines
    Public Property AutoKey As Nullable(Of Integer)
    Public Property SourceSystem As String
    Public Property SrcRefDocNr As String
    Public Property POSNR As String
    Public Property ExportDate As Date
    Public Property ExportTime As System.TimeSpan
    Public Property MATNR As String
    Public Property WERKS As String
    Public Property LFIMG As Nullable(Of Decimal)
    Public Property MEINS As String
    Public Property LGORT As String
    Public Property VRKME As String
    Public Property MTART As String
    Public Property BRGEW As Nullable(Of Decimal)
    Public Property NTGEW As Nullable(Of Decimal)
    Public Property GEWEI As String

End Class
