'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceOut_DeliveryHdr
    Public Property AutoKey As Integer
    Public Property SourceSystem As String
    Public Property SrcRefDocNr As String
    Public Property LoadingTime As Date
    Public Property WERKS As String
    Public Property LoadingBay As String
    Public Property DriverName As String
    Public Property TruckRegNo As String
    Public Property Trailer1RegNo As String
    Public Property Trailer2RegNo As String
    Public Property OperatorID As Nullable(Of Integer)

End Class
