'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class zTraceIn_SAPConfirmations
    Public Property SysID As String
    Public Property MANDT As String
    Public Property MBLNR As String
    Public Property MJAHR As String
    Public Property ZEILE As String
    Public Property MATNR As String
    Public Property WERKS As String
    Public Property LGORT As String
    Public Property CHARG As String
    Public Property BWART As String
    Public Property BUDAT As String
    Public Property SHKZG As String
    Public Property ERFMG As Nullable(Of Decimal)
    Public Property ERFME As String
    Public Property VGART As String
    Public Property BUKRS As String
    Public Property GJAHR As String
    Public Property MONAT As String
    Public Property CPUDT As Nullable(Of Date)
    Public Property CPUTM As String
    Public Property Export_Date As Nullable(Of Date)
    Public Property Export_Time As String
    Public Property BUDAT_date As Nullable(Of Date)
    Public Property FinPerKey As String
    Public Property ERFMGKgVal As Nullable(Of Decimal)
    Public Property ConfShiftId As String
    Public Property ReadStatus As String

End Class
